language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t spacefox42/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true spacefox42/react-test npm test

after_success:
  - docker build -t spacefox42/multi-client ./client
  - docker build -t spacefox42/multi-nginx ./nginx
  - docker build -t spacefox42/multi-server ./server
  - docker build -t spacefox42/multi-worker ./worker

  # Login to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #  Take those images and push them to Docker Hub
  - docker push spacefox42/multi-client
  - docker push spacefox42/multi-nginx
  - docker push spacefox42/multi-server
  - docker push spacefox42/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "Dockermulti-env"
  bucket_name: "elasticbeanstalk-us-east-1-133678316947"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY