language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t spacefox42/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true spacefox42/react-test npm test

after_success:
  - docker build -t spacefox42/multi-client ./client
  - docker build -t spacefox42/multi-nginx ./nginx
  - docker build -t spacefox42/multi-server ./server
  - docker build -t spacefox42/multi-worker ./worker