version: "3"
services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=$PGPASSWORD
  redis:
    image: 'redis:latest'
  nginx:
    depends_on:
      - api
      - client
    restart: always
    image: "spacefox42/multi-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
  api:
    image: "spacefox42/multi-server"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  client:
    image: "spacefox42/multi-client"
    mem_limit: 128m
    hostname: client
    environment:
      - WDS_SOCKET_PORT=0
  worker:
    image: "spacefox42/multi-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT